name: Telegram Notification

on:
  workflow_dispatch:

jobs:
  telegram-notify:
    runs-on: ubuntu-latest
    steps:
      - name: Telegram Notification
        uses: appleboy/telegram-action@master
        with:
          to: ${{ secrets.TELEGRAM_TO }}
          token: ${{ secrets.TELEGRAM_TOKEN }}
          message: |
            🚀 **Commit Pushed**
            
            👤 **User:** ${{ github.actor }}
            📝 **Message:** ${{ github.event.head_commit.message }}
            📂 **Repo:** ${{ github.repository }}
            
            🔗 [View Commit](https://github.com/${{ github.repository }}/commit/${{ github.sha }})
